### PR TITLE
Add preview functionality to dialog Colorize

### PR DESCRIPTION
**Pull request by Lulu04**

### CODE REVIEW

**Comment by Lulu04** [comment]
Hi, another dialog.
Nice the new hypocycloid renderer function. But, I don't understand why 'Hypocycloid' and 'Cusps:' entries in the po files are in the pull request I've just created...?

**Comment by circular17** [comment]
Hi Lulu,

It all looks fine to me, so I'll proceed with merge. Yes the hypocycloid looks nice!

It is normal that there are hypocycloid entries because on my computer on MacOS, some entries are not kept in the po file, so I avoid including them in the commits. When you build on your computer, it does updates the po files without this problem, so your po files are just what I need!

**Comment by Lulu04** [comment]
Hi, so all is fine about the po files!

I think all the dialogs that can have preview functionality are done. If you agree with this, should I delete the branch `dev-showhidepreview` ?

I would like to continue contributing to LazPaint. How should I proceed, for example if I have a solution to one of the issues mentioned by the users?

**Comment by circular17** [comment]
All the dialogs with preview functionality look great. Excellent work!

Sure, go ahead and delete the `dev-showhidepreview` branch, given that we've addressed its objectives. If ever, we can still make a new branch and the history is preserved in LazPaint repository.

I'm glad to hear you're keen on continuing with LazPaint. I've added you as a member of the LazPaint repository. So, if any issue inspires you, feel free to assign it to yourself.

Should you have any questions or require clarifications, or just would like to chat, please don't hesitate to write directly within the issue thread.

When you're ready to dive into coding, you can create a branch on your repository, just like you did before, with a descriptive name with `dev-` prefix.

Welcome aboard the project!

**Comment by Lulu04** [comment]
Thanks Captain Circular!

I've accepted your invitation to become a member, although it scares me a bit, I don't know github very well and don't want to do anything stupid with the repository!

Anyway, thanks for the promotion!

**Comment by circular17** [comment]
Lulu04, it's perfectly natural to have some hesitations when starting with GitHub. But don't worry, with the "Triage" role, you won't have permissions to make any irreversible changes to the main repository. Your role will mainly allow you to manage and categorize issues or pull requests without having to modify the repository's code directly.

**Pull request merged**
