### PR TITLE
Added Preview functionality to other filters

### PR DESCRIPTION
**Pull request by Lulu04**
Hi, here the changes for other filters.
Regarding the filters using it, I preferred not to modify the code of TFilterThreadManager.

### CODE REVIEW

**Comment by circular17** [comment]
Thanks for the pull request. I am looking at the code.

**Comment by Lulu04** [comment]
Hi Circular,
Ok. I'm happy to have contributed a little. It was a first for me. A few moments of panic, but very instructive. I'll keep going if I get any more ideas!
Regards

**Comment by Lulu04** [comment]
Hi Circular, thank you for your feedback.
I've merged your commits into my local dev-showhidepreview branch ( 😎 ) and to get a better overview. I'll have a better look tomorrow.
Regards

**Comment by Lulu04** [comment]
Hi, ok I understand: in radial blur filter, when OnTaskEvent(...) receive tmeCompletedTask event, its not necessary to duplicate the computed image since we have our preview checkbox checked. It will be duplicated when user uncheck the preview.
Introducing the 2 methods makes the code easier to read. Well done!
I'll make the adjustments in the other blur filters.

**Comment by circular17** [comment]
Hi Lulu,

Exactly, you've grasped the essence of the changes! That's the optimization I was aiming for, the current image indeed already holds the changes while the preview is active. I'll review the adjustments you've made to other filters. It's wonderful to see LazPaint's code being refined!

**Pull request merged**
