### PR TITLE
Fix compilation errors (procedure GetFilesInDir)

### PR DESCRIPTION
**Pull request by rchastain**
A quick modification, to be able to compile LazPaint under Linux. Made in five minutes. Needs to be approved by an expert. ;)

### CODE REVIEW

**Comment by circular17** [comment]
Thanks.

Indeed, there are other files changes. Before making a pull request, I recommend to go though the changes. If you don't have a tool that shows you that, there is GitKraken which is free for opensource projects.

Also you need to make the pull request against "dev-lazpaint" branch.

But anyway, I guess I understand your changes.

**Comment by rchastain** [comment]
Thank you for the informations.

So, I think I can close the PR?

And I think I will delete my fork and start a new one. Otherwise I don't know how to synchronize again with the source repository.

About GitKraken, I read [here](https://www.gitkraken.com/download/linux-rpm) that there is a "free 7-day trial"...

**Comment by circular17** [comment]
Yes you would need to recreate the fork.

I am installing a virtual machine on Linux to look into it.

**Comment by rchastain** [comment]
Thank you for the confirmation.

**Comment by circular17** [comment]
You're welcome

**Comment by circular17** [comment]
Hmmm I am confused, I did compile successfully with Lazarus 2.2.2

**Comment by rchastain** [comment]
Please could you tell me the procedure for creating PR?

I tried this but it doesn't seem to be correct.

```
[roland@localhost sources]$ git clone git@github.com:rchastain/lazpaint.git lazpaint-r
Clonage dans 'lazpaint-r'...
...
[roland@localhost sources]$ cd lazpaint-r
[roland@localhost lazpaint-r (master)]$ git checkout dev-lazpaint
error: le spécificateur de chemin 'dev-lazpaint' ne correspond à aucun fichier connu de git
[roland@localhost lazpaint-r (master)]$ 
```

When I created the fork, there was a checkbox checked "copy only the master branch". Should I have unchecked it?

**Comment by circular17** [comment]
I create the branches and do the pull requests using GitHub website. I am not sure about the command line syntax.

**Comment by circular17** [comment]
Oh I see, fork is on the whole repository. So yes I suppose you need to uncheck "copy only the master branch"

**Comment by rchastain** [comment]
OK. I re-deleted and re-created my fork, with "only master" unchecked. Now I can see all the branches.

See you soon.

**Comment by circular17** [comment]
Cool

**Comment by rchastain** [comment]
> Hmmm I am confused, I did compile successfully with Lazarus 2.2.2

I understand now why you were confused. Indeed, as I said in the other discussion, compilation successful with Lazarus 2.2.2. Sorry for the confusion.

Lazarus 2.0.10 is the current version for my Linux distribution (Mageia).

**Comment by circular17** [comment]
Ok I see.

It is complicated to keep backward compatibility. But maybe we can do something with compiler directives.

**Comment by rchastain** [comment]
> But maybe we can do something with compiler directives.

Up to you. For me, I don't really need it.

**Comment by circular17** [comment]
Ok I will see later then

**Pull request closed without merging**
