### PR TITLE
Dev showhidepreview

### PR DESCRIPTION
**Pull request by Lulu04**
I wanted the different commits to be separate, but apparently that didn't work... To do this, should I do:

- push my first commit
- create  the pull request
- then push the following commits.
Is this correct?

I've reworked the filter code as you suggested. Hopefully it's all right.

### CODE REVIEW

**Comment by circular17** [comment]
Hi Lulu,

Other commits you push on this branch will be added to this pull request automatically. To have the commits in a different pull request, you would need to keep the next changes locally (not "pushing" them). Or you can use another branch.

But that's ok, each commit is displayed here with its own line and I can review them independently. They are neatly named that's perfect.

I will have a look at the code shortly

Best regards

**Comment by Lulu04** [comment]
I now understand better the relationship between branch/pull request/commits. Thank you for your explanations and your patience!
Regards

**Comment by circular17** [comment]
You're welcome, Lulu. Thanks for being patient as well.

I've reviewed the changes and they're on point. I'll be merging them in and running tests on each window. Great work!

**Comment by circular17** [comment]
I've done some tests and all seem to function as intended.

**Pull request merged**
