### PR TITLE
load/save color-key association to config file

### PR DESCRIPTION
**Pull request by Lulu04**
Hi Circular, here the happy coding!

I follow your advices. Please check for possible happy bugs, procedure naming etc...

Regards

### CODE REVIEW

**Review by circular17 — COMMENTED** [review]
Hi Lulu! Here is the happy review!

Your code makes a lot of sense. I only have a few suggestions of improvement.

I understand that by (Pos(FKeyPrefix,varName) = 1) you check that varName starts with FKeyPrefix. There is a wonderful new method to do that : varName.StartsWith(FKeyPrefix).

Regarding the storage in TVariableSet there are functions/properties to store pixel values like vars.Pixels[...] := ....

I wish you a happy morning!

**Comment by Lulu04** [comment]
Hi Circular,

> There is a wonderful new method to do that : varName.StartsWith(FKeyPrefix).

You're right, it's much more meaningful. Thanks for the tip!

> Regarding the storage in TVariableSet there are functions/properties to store pixel values like vars.Pixels[...] := ....

My first attempt was to use `vars.Pixels[...]` but the color was saved without the alpha channel. I thought this would be a problem when the palette is in transparent mode.

After reading your comment, I took a closer look at the `BGRAToStr function` and in particular the way its `AOptionalAlpha` parameter is handled. I now understand that with `AOptionalAlpha` set to `TRUE`, an alpha channel equal to 255 is ignored and is incorporated if it's different.
All is fine! I'll do the change. Thanks!

Regards

**Comment by circular17** [comment]
Hi Lulu,

I understand your thought process about the alpha value. The reason not to always include the alpha channel was to make the color more web like #RRGGBB.

I see you've made the change when writing a color, though not when reading it. I presume you forgot. Shall I wait a bit more before merging?

Regards

**Comment by circular17** [comment]
Hi Lulu,

I am surprised, I checked again and now I see indeed the use of Pixels. Maybe the page was not refreshed. Anyway it looks good to me. I've merged the changes.

Thank you this improvement of the association of colors with digits!

Warm regards

**Comment by Lulu04** [comment]
Hi,
a GitHub joke! 
Thank you for the merge.

Regards

**Pull request merged**
