### PR TITLE
add github-ci and dependabot

### PR DESCRIPTION
**Pull request by theavege**
<b>Hello!</b>

Thanks for your project. I add github-actions and dependabot for github-actions. I hope it is useful.

<i>Thanks.</i>

### CODE REVIEW

**Comment by theavege** [comment]
@BobanSpasic Could you accept the PR?

**Comment by theavege** [comment]
@BobanSpasic Could you accept the PR?

**Comment by BobanSpasic** [comment]
> @BobanSpasic Could you accept the PR?

Hi @theavege 
I am not involved in LazPaint development

**Comment by theavege** [comment]
Not answer

**Comment by circular17** [comment]
Hello @theavege 

Apologies for the late reply. I've not been working on the project very much and somehow I didn't get the notifications.

If I understand, your proposal could indeed improve the workflow by ensuring the project compiles. Am I correct?

Warm regards

**Comment by theavege** [comment]
@circular17 I'm really happy that you replied to me. You are correct. If you wish,  I can send a new PR. Are you interested in this?

**Comment by theavege** [comment]
@circular17 I think you might be interested also solution "[setup-lazarus](https://github.com/gcarreno/setup-lazarus)" @gcarreno, because it's there:
- [doublecmd](https://github.com/doublecmd/doublecmd)
- [Hex](https://github.com/wp-xyz/Hex)

**Comment by circular17** [comment]
I'm trying out github actions on the [DimPas](https://github.com/circular17/DimPas) project with your pull request.

**Pull request closed without merging**
