### PR TITLE
Added Preview functionality to filter Pixelate

### PR DESCRIPTION
**Pull request by Lulu04**

### CODE REVIEW

**Comment by circular17** [comment]
The idea to add rsPreview for the caption of the checkbox is interesting, it avoids creating new entries in the po files for every checkbox with this caption. Well done!

The way you implemented the checkbox makes a lot of sense.

I note that inadvertently the file _lazpaint.fr.mo_ was added. I would rather not include mo files for now as the information is included in the po file. Can you remove the mo file in your branch? This will update the pull request automatically.

**Comment by circular17** [comment]
Once this minor point is dealt with, I will merge the request. Thank you for your first contribution!

**Comment by Lulu04** [comment]
Sorry for my late answer, I did not know we have a thread here too!

> The idea to add rsPreview for the caption of the checkbox is interesting, it avoids creating new entries in the po files for every checkbox with this caption. Well done!

This complicates the code a little but makes translations easier. Redundancies of 'ok', 'cancel' or other in po files could be avoided by doing this and using Lazarus Project options>i18n>Excluded>Identifiers or Originals lists.

> I note that inadvertently the file _lazpaint.fr.mo_ was added. I would rather not include mo files for now as the information is included in the po file. Can you remove the mo file in your branch? This will update the pull request automatically.

Do I have to do this from the forked remote repository or from the forked local repo on my computer?

**Comment by circular17** [comment]
Ok, I can see how the separate thread might not have been immediately obvious. It's indeed helpful sometimes to have a dedicated space to discuss specifics of a pull request.

Regarding the redundancies in po files, your approach of simplifying translations sounds promising. It would be interesting to see if it removes only the duplicates. As it's a low-priority enhancement, we can look into it later.

As for removing the mo file, you can choose either method. If you're more comfortable working in your local repo, make the change there and then push the update. Alternatively, you can make the change directly from GitHub's interface. Whatever feels easier for you!

**Comment by Lulu04** [comment]
Ok, I think its done :)

**Comment by Lulu04** [comment]
Hi Circular,
before validating this pull request, about the modified Pixelate filter, now there is a checkbox without caption (in the form under the IDE). May be this is not a problem with this window with small number of controls inside. It can become annoying for a new contributor in a bigger windows with lot of controls. This can be avoided by :

- setting CheckBox_Preview.Caption to 'rsPreview' in the form TFPixelate
- adding 'rsPreview' in Lazarus Project options>i18n>Excluded>Originals list to ask Lazarus to not translate this string.

At runtime, when the form is opened the caption is initialized by code like we have done in the pull request.
If you are agree, I can complete the pull request with the proposed change.

**Comment by lainz** [comment]
Hi. My question is if that I 18 setting 'exclude' is available in Lazarus 3.0 since lazpaint in compiled with releases.

**Comment by Lulu04** [comment]
Hi Lainz, I don't know my Lazarus version is 2.2.4. I've read the Lazarus 3.0 changes, nothing is mentioned about this.
I've just asked on the forum, let's wait for the answer.
Thank you Lainz to mention this possible issue. I'm not very familiar with all the details that need to be taken into account, so my contribution will be limited... :)

**Comment by lainz** [comment]
Hi so It's already available in current release. I don't think they will remove such features.

**Comment by Lulu04** [comment]
I don't think so either, this feature has been around for a long time

**Comment by circular17** [comment]
Hi Lulu and Lainz,

I did not realize you would have answered already. Sorry for the late reply.

It is reassuring to know that the feature of filtering entries of i18n is stable.

Thanks Lulu for going into the details of how this filtering would be used to exclude translations. I understand now that in the checkbox caption, the name rsPreview of the resource string would be put, not the actual caption. So it is possible to exclude this name from the translation and this will not affect the entry for the value of rsPreview.

I think it is a clever idea and that we can indeed start to use it. I invite you to go ahead try it out! If you have other things in the branch and you prefer not to merge, it is okay, we can merge what you've already done.

Cheers

**Comment by Lulu04** [comment]
After some github confused situations... here it is!
Please check that the translations of ok and cancel have not been lost in the po files of the supported languages. I did, but just to be sure.

**Comment by circular17** [comment]
Ok. I am glad the confusions have disappeared. I suppose we haven't talked about those and that you resolved them on your own showing autonomy.

I did a double check and all seems fine to me as well. Well done! 

I will proceed and merge.

**Comment by Lulu04** [comment]
Hi, I'm happy the first filter is merged!
Let's continue! Can I send several filters on the same pull request?

**Comment by circular17** [comment]
Hi Lulu! Indeed, this thread is for the pull request. No worries about the mix-up! We can celebrate the merge here 👍 For further discussions, the issue threads would be the best place.

**Pull request merged**
