### PR TITLE
Added flatpak packaging files and updated snap files

### PR DESCRIPTION
**Pull request by chronoscz**
This change will allow us to package LazPaint as flatpak to be published on Flathub.
There are also included some snap package updates.

### CODE REVIEW

**Comment by chronoscz** [comment]
Flathub pull request: https://github.com/flathub/flathub/pull/5939

**Comment by chronoscz** [comment]
Flathub submission was accepted and merged. LazPaint is now available for download on Flathub https://flathub.org/apps/io.github.bgrabitmap.LazPaint

**Comment by chronoscz** [comment]
To verify that the app is published by original authors either I need to be admin of this Github repository or you should create a new file https://bgrabitmap.github.io/.well-known/org.flathub.VerifiedApps.txt with content ad6a826f-51d9-456e-99a3-50aca6b61d0c. Can you please do the one of the those?

**Comment by lainz** [comment]
Hi, I've invited you to be part of this organization.

**Comment by chronoscz** [comment]
Thanks. The app is not verified https://flathub.org/apps/io.github.bgrabitmap.LazPaint

**Comment by circular17** [comment]
Thank you very much indeed for adding flatpack and snap support! Regarding the patches, I presume they will need to be updated so I will come back to you when I release a new version. Welcome onboard!

Warm regards

**Comment by chronoscz** [comment]
Hi, as new releases are not that often I will watch it and update both snap and flatpak. I also watch Lazarus forum so I should notice new releases.
I don't see Settings tab on that github lazpaint flathub repo so I can't invite other people to have merge access. Probably we would need to ask their support to do that.

**Pull request merged**
