### PR TITLE
Fixing translations

### PR DESCRIPTION
**Pull request by lainz**
Ok, in the bugtracker Maxim Ganetsky helped me to find the bug.

The problem was that in the projects the .lrj files was in the gitignore, and these .lrj files are needed to create the translations, so these files must be shipped with the sourcecode as well.

So the solution is to open every single form in the project, move something a button or a component, then save the form. Then a .lrj file is created.

Then rebuild the program and the .po file is correctly generated!

### CODE REVIEW

**Comment by circular17** [comment]
Cool. I will have a look and check all translations are preserved.

**Comment by lainz** [comment]
Thanks. If the translations are missing something, just commit the LRJ files, and let the po files as they are now. Not sure on how can you do that. If is not easy with git, just make a copy of the translations into a separate folder, then merge, then revert the .po files.

**Comment by lainz** [comment]
Or another way, grab the .lrj files, copy them into a separate folder, remove this merge and the branch, and just copy the .lrj files in the dev branch.

**Comment by circular17** [comment]
Well that would result in the same thing. Simpler to look at the diff of your branch.

**Comment by lainz** [comment]
Indeed =)

Just to make sure I did not forget any form.

**Comment by circular17** [comment]
I may also have kept translations even if they are not used anymore in the software. Maybe I need to add some "const" to preserve them.

**Comment by lainz** [comment]
With resourcestrings there is no problem. Just keep them. With forms is another story.

**Comment by circular17** [comment]
There was just one translation that wasn't used, the hint on the color description (CSS notation). I had forgotten to display it when I refactored the component. I paste here a copy:

de;Farbbeschreibung: Anklicken, um Farbnamen oder CSS Farbcode mit der Tastatur einzugeben.
ar; وصف اللون : انقر  في اللون مع لوحة المفاتيح باستخدام أسماء الألوان أو بتدوين CSS.
es;Descripción del color: hacer clic para escribir el nombre de un color o usar notación CSS.
sv;Färgbeskrivning: klicka för att skriva in en färg med tangentbordet genom färgnamn eller CSS-notation
fr;Description de la couleur : cliquez pour entrer une couleur avec le clavier en utilisant les noms de couleurs ou la notation CSS.
en;Color description: click to type in a color with the keyboard using color names or CSS notation.
nl;Kleurbeschrijving: klik om een kleur in te typen met het toetsenbord middels kleurnamen of CSS notatie.
cs;Popis barvy: klikněte pro zadání barvy klávesnicí pomocí jména barvy nebo zápisu CSS.
zh;颜色说明：单击以键入颜色名称或 CSS 表示。
pt;Descrição Cor: clique para digitar uma cor com o teclado usando nomes de cores ou a notação CSS.
pl;Opis koloru: kliknij, aby wpisać kolor za pomocą klawiatury, używając nazw kolorów lub notacji CSS.
lv;Krāsas apraksts: ieklikškini, lai ierakstītu krāsas vārdu angliski vai CSS pierakstā.
kab;Aglam n yini: sit iwakken ad teskecmeḍ ini s unasiw s yismawen-nnsen neɣ s tira n CSS.
bg;Описание на цвета: цъкнете, за да напишете цвят по име или по CSS означение.

**Pull request merged**
