### PR TITLE
Czech translation update

### PR DESCRIPTION
**Pull request by chronoscz**

### CODE REVIEW

**Comment by circular17** [comment]
Thanks. I notice some translations are removed in the source branch, this can happen when building the program. Can you restore them?
```
#: tablet.getprocfailed
#, object-pascal-format
msgid "Procedure %s failed to load properly."
msgstr "Nepodařilo se správně načíst proceduru %s."

#: tablet.openfailed
msgid "Tablet context failed to open."
msgstr "Nelze otevřít kontext tabletu."
```

**Comment by chronoscz** [comment]
Ok, that was the problem. I have updated the file from .pot and made more corrections.

**Comment by circular17** [comment]
Thanks. I notice that many "msgctxt" are removed. I suppose it means context, and it doesn't matter when there is only one "msgid" with a specific string. So I will merge.

**Comment by chronoscz** [comment]
Thanks. Yes, I used Poedit and update from pot file. If you compare this file and main pot file then it should match except translated texts and header. Not sure how exactly those msgctxt fields are generated.

**Comment by circular17** [comment]
I suppose they are generated using the names of the form controls. The pot file was generated recently so maybe the simplification algorithm is applied whereas it wasn't the case before. Anyway if it works when you use LazPaint, that's great.

**Pull request merged**
